
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-03T12:05:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "81cfe74866b1b0cfcb1cf22d9dccc8228d0ddd6a",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
