# This environment file enables Manila with the Netapp backend.
resource_registry:
  OS::Tripleo::Services::ManilaApi: ../puppet/services/manila-api.yaml
  OS::Tripleo::Services::ManilaScheduler: ../puppet/services/manila-scheduler.yaml
  # Only manila-share is pacemaker managed:
  OS::Tripleo::Services::ManilaShare: ../puppet/services/pacemaker/manila-share.yaml
  OS::Tripleo::Services::ManilaBackendNetapp: ../puppet/services/manila-backend-netapp.yaml

parameter_defaults:
  ManilaNetappEnableBackend: true
  ManilaNetappBackendName: tripleo_netapp
  ManilaNetappDriverHandlesShareServers: true
  ManilaNetappLogin: ''
  ManilaNetappPassword: ''
  ManilaNetappServerHostname: ''
  ManilaNetappTransportType: 'http'
  ManilaNetappStorageFamily: 'ontap_cluster'
  ManilaNetappServerPort: 80
  ManilaNetappVolumeNameTemplate: 'share_%(share_id)s'
  ManilaNetappVserver: ''
  ManilaNetappVserverNameTemplate: 'os_%s'
  ManilaNetappLifNameTemplate: 'os_%(net_allocation_id)s'
  ManilaNetappAggrNameSearchPattern: '(.*)'
  ManilaNetappRootVolumeAggr: ''
  ManilaNetappRootVolume: 'root'
  ManilaNetappPortNameSearchPattern: '(.*)'
  ManilaNetappTraceFlags: ''
  ManilaNetappEnabledShareProtocols: 'nfs3, nfs4.0'
  ManilaNetappVolumeSnapshotReservePercent: 5
  ManilaNetappSnapmirrorQuiesceTimeout: 3600
