
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-15T00:00:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b83b34177efdaeda5a3ccffc54a86c436b29570c",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
