# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tabWidget(object):
    def setupUi(self, tabWidget):
        tabWidget.setObjectName("tabWidget")
        tabWidget.resize(508, 1155)
        tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabInput = QtWidgets.QWidget()
        self.tabInput.setObjectName("tabInput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabInput)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageBox = QtWidgets.QGroupBox(self.tabInput)
        self.imageBox.setObjectName("imageBox")
        self.gridLayout = QtWidgets.QGridLayout(self.imageBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.imageBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.bkgEdit = QtWidgets.QLineEdit(self.imageBox)
        self.bkgEdit.setObjectName("bkgEdit")
        self.gridLayout.addWidget(self.bkgEdit, 3, 1, 1, 1)
        self.openDarkButton = QtWidgets.QToolButton(self.imageBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/folder"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openDarkButton.setIcon(icon)
        self.openDarkButton.setAutoRaise(True)
        self.openDarkButton.setObjectName("openDarkButton")
        self.gridLayout.addWidget(self.openDarkButton, 1, 2, 1, 1)
        self.floodEdit = QtWidgets.QLineEdit(self.imageBox)
        self.floodEdit.setObjectName("floodEdit")
        self.gridLayout.addWidget(self.floodEdit, 2, 1, 1, 1)
        self.darkEdit = QtWidgets.QLineEdit(self.imageBox)
        self.darkEdit.setObjectName("darkEdit")
        self.gridLayout.addWidget(self.darkEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.imageBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.frameEdit = QtWidgets.QLineEdit(self.imageBox)
        self.frameEdit.setObjectName("frameEdit")
        self.gridLayout.addWidget(self.frameEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.imageBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.openFloodButton = QtWidgets.QToolButton(self.imageBox)
        self.openFloodButton.setIcon(icon)
        self.openFloodButton.setAutoRaise(True)
        self.openFloodButton.setObjectName("openFloodButton")
        self.gridLayout.addWidget(self.openFloodButton, 2, 2, 1, 1)
        self.floodCheckBox = QtWidgets.QCheckBox(self.imageBox)
        self.floodCheckBox.setText("")
        self.floodCheckBox.setObjectName("floodCheckBox")
        self.gridLayout.addWidget(self.floodCheckBox, 2, 3, 1, 1)
        self.openFrameButton = QtWidgets.QToolButton(self.imageBox)
        self.openFrameButton.setIcon(icon)
        self.openFrameButton.setAutoRaise(True)
        self.openFrameButton.setObjectName("openFrameButton")
        self.gridLayout.addWidget(self.openFrameButton, 0, 2, 1, 1)
        self.openBkgButton = QtWidgets.QToolButton(self.imageBox)
        self.openBkgButton.setIcon(icon)
        self.openBkgButton.setAutoRaise(True)
        self.openBkgButton.setObjectName("openBkgButton")
        self.gridLayout.addWidget(self.openBkgButton, 3, 2, 1, 1)
        self.bkgCheckBox = QtWidgets.QCheckBox(self.imageBox)
        self.bkgCheckBox.setText("")
        self.bkgCheckBox.setObjectName("bkgCheckBox")
        self.gridLayout.addWidget(self.bkgCheckBox, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.imageBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.darkCheckBox = QtWidgets.QCheckBox(self.imageBox)
        self.darkCheckBox.setText("")
        self.darkCheckBox.setObjectName("darkCheckBox")
        self.gridLayout.addWidget(self.darkCheckBox, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.imageBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        tabWidget.addTab(self.tabInput, "")

        self.retranslateUi(tabWidget)
        tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabWidget)

    def retranslateUi(self, tabWidget):
        _translate = QtCore.QCoreApplication.translate
        tabWidget.setWindowTitle(_translate("tabWidget", "Parameters"))
        self.imageBox.setTitle(_translate("tabWidget", "Image"))
        self.label.setText(_translate("tabWidget", "Frame:"))
        self.openDarkButton.setText(_translate("tabWidget", "..."))
        self.label_2.setText(_translate("tabWidget", "Background:"))
        self.label_3.setText(_translate("tabWidget", "Dark:"))
        self.openFloodButton.setText(_translate("tabWidget", "..."))
        self.openFrameButton.setText(_translate("tabWidget", "..."))
        self.openBkgButton.setText(_translate("tabWidget", "..."))
        self.label_4.setText(_translate("tabWidget", "Flood:"))
        tabWidget.setTabText(tabWidget.indexOf(self.tabInput), _translate("tabWidget", "Input"))

from . import resources_rc

