version: '2'
services:
  mdm_server:
    image: filewave/fw-mdm-server:${FILEWAVE_VERSION}
    container_name: "fw_mdm_server_${FILEWAVE_VERSION}"
    networks:
      - mdm_net

    ports:
      - 2195:2195
      - 9432:9432
      - 5223:5223
      - 19995:19995
      - 19996:19996
      - 20005:20005
      - 20006:20006
      - 20015:20015
      - 20016:20016
      - 20017:20017
      - 20443:20443
      - 20445:20445
      - 20446:20446
      - 20030:20030

    restart: unless-stopped

    volumes_from:
      - mdm_data

  mdm_data:
    image: filewave/fw-mdm-data-volume:${FILEWAVE_VERSION}
    container_name: "fw_mdm_data"
    networks:
      - mdm_net

networks:
  mdm_net:
  
