client_id: 7kOWk6-k4jFRaDUmNKjKTcsqlIJZgFwt
client_secret: ioroqeJZq3k5d11glKvnaa2GBYKYA3FU56Rjbe14
redirect_url: https://uberapitester.com/api/v1/uber/oauth
scopes:
    - profile
    - history
    - places
    - request
    - request_receipt
    - all_trips
