# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0011_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
