
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-08T20:43:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "070cad88e8a0ada1eb22e4626814cfa27214c964",
 "version": "1.99.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
