# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviantart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
