# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviantart', '0002_token_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
