# This file was auto-generated by salt's setup on Monday, 31 October 2016 @ 22:10:33 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2016, 3, 4, 0, 0, 0, None)
