
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-04T13:54:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4c4924477854dee5b2ec71bfe82e62216c3d882",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
