# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=4096, unique=True, verbose_name='URL')),
                ('code', models.CharField(blank=True, db_index=True, max_length=16, unique=True, verbose_name='code')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='counter')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'URLs',
                'verbose_name': 'URL',
            },
        ),
    ]
