# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='last updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('command_name', models.CharField(editable=False, max_length=255)),
                ('start_at', models.DateTimeField(editable=False)),
                ('end_at', models.DateTimeField(editable=False, null=True)),
                ('success', models.NullBooleanField(default=None, editable=False)),
                ('raw_output', models.TextField(editable=False, null=True)),
                ('stdout', models.TextField(editable=False, null=True)),
                ('stderr', models.TextField(editable=False, null=True)),
                ('traceback', models.TextField(editable=False, null=True)),
                ('reference', models.CharField(editable=False, max_length=255)),
                ('imported_by_str', models.CharField(editable=False, max_length=255)),
                ('created', models.BigIntegerField(default=0, editable=False)),
                ('read', models.BigIntegerField(default=0, editable=False)),
                ('updated', models.BigIntegerField(default=0, editable=False)),
                ('deleted', models.BigIntegerField(default=0, editable=False)),
                ('errors', models.BigIntegerField(default=0, editable=False)),
                ('imported_by_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'command log',
                'verbose_name_plural': 'command logs',
            },
        ),
    ]
