# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_commandlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlog',
            name='imported_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
