


# =========================================== Sections for the users
input_directory: "%(input_directory)s"
input_extension: "%(input_extension)s"
input_pattern: "%(input_pattern)s"
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"


compressor:
    source: fastq.gz
    target: fastq.bz2
    recursive: True

