# Configure these settings for your system, and then
# copy this file to your home directory (~).
mp_api: your_materials_project_api_key
normal_binary: /path/to/vasp/executable
twod_binary: /path/to/2D/vasp/executable
potentials: /path/to/POTCAR/files
vdw_kernel: /path/to/vdw_kernel.bindat  # Leave as is if hard-coded into VASP
queue_system: slurm  # Change to pbs if working on a pbs queue.
