
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "47df9a6e265963f0828a255782afb5bf826e904a",
 "version": "1.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
