
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "98b0e0401994529d0a644bf4153741f383fbd53f",
 "version": "0.0.0a24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
