
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.9.3',
    'branch_nick': '(detached',
    'revision_id': 'be03917b03bca5d52c2b40528c15c6ba6dada066',
    'revno': 4592
}
