# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypnobox', '0002_auto_20160909_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='product id'),
        ),
    ]
