# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 19:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypnobox', '0004_lead_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[\\d\\-]+$', message='Only numbers.')], verbose_name='phone number'),
        ),
    ]
