
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4501f873a4ee94500a34e9b8830ce255023cc846",
 "version": "0.7.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
