language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
install:
    - pip install zc.buildout
    - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]];
      then
        buildout;
      else
        buildout parts=test;
      fi
script:
    - bin/test
    - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]];
      then
        cd docs;
        make SPHINXBUILD=../bin/sphinx-build doctest;
      fi
notifications:
    email: false
cache:
  directories:
    - eggs
