app:
  image: hardikgajjar/magento2-nginx
  hostname: {{ project_name }}_nginx
  links:
    - phpfpm
    - db
    - redis
    - memcached
  volumes_from:
    - appdata
  environment:
    VIRTUAL_HOST: {{ project_name }}.docker
    VIRTUAL_PORT: 80

phpfpm:
  image: hardikgajjar/magento2-phpfpm
  hostname: {{ project_name }}_phpfpm
  links:
    - db
    - redis
    - memcached
  volumes_from:
    - appdata
  environment:
    M2SETUP_DB_HOST: db
    M2SETUP_DB_NAME: magento
    M2SETUP_DB_USER: magento
    M2SETUP_DB_PASSWORD: magento
    M2SETUP_BASE_URL: http://{{ project_name }}.docker/
    M2SETUP_BACKEND_FRONTNAME: admin
    M2SETUP_ADMIN_FIRSTNAME: Admin
    M2SETUP_ADMIN_LASTNAME: User
    M2SETUP_ADMIN_EMAIL: magento-admin@example.com
    M2SETUP_ADMIN_USER: admin
    M2SETUP_ADMIN_PASSWORD: admin123

db:
  image: mariadb:10.0
  hostname: {{ project_name }}_db
  ports:
    - "8001:3306"
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: magento
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: magento

redis:
  image: redis
  expose:
    - 6379

memcached:
  image: memcached
  expose:
    - 11211

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

appdata:
  image: tianon/true
  volumes:
    - ./:/var/www
    - ~/.composer:/root/.composer
