language: python
python: 3.4
install:
- pip install -U tox
script: tox
deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: FFManngbsvt+wIHSoMTg1+XnkXA4Og7SaxRck1VtA2JKnNJMMApZ0WadibxBy8EI2ZXE0tBxpNOQe7Ey86ivxRL3+MWS8aUu2GIeoEF7P7870ZqWk776FcC8W9OvmYIZ31PfctcSNLvm0pDPNGLfd8EyXphlNxaI/d485tYcvyBIk8e/AvKrJHvOMJyZ1hYhFUpyt8pfGsgTrK+AmcetahBkuLS5FmPPYxtZ5vTLoLvLTH3NgCXF1H2dxTUgAIOZSKISWJPMUYQ5PZyzzvMnV6L6Xb5kFTBm2Bqp38tsay7MGx2GPTjSS/+RxEO+WH+9Jg0ADue9mVFMaYUihuv4zYeW1eNr7MKbYh5iCH0Kn3AWiAuUPYqtubgV3haxXj1L1gIMt8vs1W1r+BAweaVKDYn5P+NzrRGPtBQWns1VV9xxYLLsgfAlnuUlgHt0Gv5H+Ibb4BWTjVK1JsowgZhEQfmM9wU6xHrLaAlPAEdDR9/9VAUDG7KrYbRS/Rtvn2MWr722yQt5+DFlpQaPvPa3/tR53dkkv/7+l2YmPTkDVFNg+XpmA/BWK+/dB2GnIJL0RM/hE1elHI0GqTqDi996YWm/h5YK1KnnFOodHaJd+wHVV2uawoaaInOqJS9vn+TwQymFvfwOOMGB4Idx9LI+z6ez8M114IXhZ+uK70kwUgs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: internap/artifactory-ephemerals-pruner
