# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('text_de_de', models.CharField(max_length=64, null=True)),
                ('text_en_gb', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
