# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Example: 5 or 0,05', max_digits=4, verbose_name='Percent discount')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='For unlimited, not necessary', null=True, verbose_name='End date')),
                ('promo_codes', models.TextField(blank=True, default='', help_text='In this field, it will be generated promo-codes', verbose_name='Promo-codes')),
                ('use_promo_codes', models.BooleanField(default=False, verbose_name='Use promo-codes ?')),
                ('count_promo_codes', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Count promo-codes')),
                ('only_registered', models.BooleanField(default=False, verbose_name='Only registered users ? - (Promo-codes)')),
                ('not_delete_promo_codes', models.BooleanField(default=False, verbose_name='Not delete promo-codes ?')),
                ('unlimited', models.BooleanField(default=False, verbose_name='Unlimited ? - (Date)')),
                ('active', models.BooleanField(default=True, verbose_name='Active discount')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('start_date', 'id'),
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
