language: python
python:
  - "3.5"
  - "3.6-dev"

install:
  - pip install tox coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6-dev ]]; then tox; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6-dev ]]; then tox -e py36-pytest28,py36-pytest29,py36-pytest30; fi

after_success:
  - coveralls

deploy:
  provider: pypi
  user: nicoddemus
  password:
    secure: bB4adUZVIkt31cmNklskyIDNehujKToGnStnlunp7P8CBF6CGeNqkYU17emAPvfZbTb/ClUpiO9r6AD1ej32Uyr+I8qUyhuYtHG3JGp+WRR/tw+ytAZIJ9i+PMjBv1RAdyLENJ/Tx0LKHKsABr8dQIieLFqKZJuT77f/5ZkvI/U=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pytest-dev/pytest-mock
    condition: $TRAVIS_PYTHON_VERSION = 3.5
