# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0006_auto_20160823_2337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messaging',
            table='djm_messaging',
        ),
    ]
