
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-24T13:25:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "44bf787b1883eaefb9ca4935c429e012011cf44d",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
