# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0004_auto_20160823_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
            ],
            options={
                'db_table': 'djm_rawbody',
            },
        ),
        migrations.DeleteModel(
            name='Callback',
        ),
    ]
