sudo: false
cache:
  directories:
    - .tox
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - travis_retry pip install tox
script:
    - tox -e py
notifications:
    email: false
