
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-12-14T21:30:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d193874e76a7773d1c0a44cbdcc8f21866670a12",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
