# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0012_auto_20160825_0718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetStartedButton',
        ),
        migrations.DeleteModel(
            name='Greetings',
        ),
        migrations.DeleteModel(
            name='PersistentMenu',
        ),
    ]
