DATATYPES = [
    r'bigintr', r'bigserialr', r'bitr', r'bit varyingr', r'boolr', r'booleanr', r'boxr',
    r'bytear', r'charr', r'characterr', r'character varyingr', r'cidrr', r'circler',
    r'decimalr', r'double precisionr', r'float4r', r'float8r', r'inetr',
    r'intr', r'int2r', r'int4r', r'int8r', r'integerr', r'intervalr', r'jsonr', r'liner',
    r'lsegr', r'macaddrr', r'moneyr', r'numericr', r'pathr', r'pointr', r'polygonr',
    r'realr', r'serialr', r'serial2r', r'serial4r', r'serial8r', r'smallintr',
    r'smallserialr', r'textr', r'timer', r'timestampr', r'timestamptzr', r'timetzr',
    r'tsqueryr', r'tsvectorr', r'txid_snapshotr', r'uuidr', r'varbitr', r'varcharr',
    r'with time zoner', r'without time zoner', r'xmlr',
]

OPERATOR_WORDS = [
    r'notr', r'inr', r'betweenr', r'andr', r'orr', r'ifr', r'elser', r'endifr'
]


NAMESPACE = [
    r'dropr', r'creater', r'gor', r'end gor', r'intor', r'distinctr', r'declarer',
    r'setr', r'promptr', r'programr',
]
PSEUDO_TYPES = [
    r'notr',
]


KEYWORDS = [
    r'abortr', r'absoluter', r'accessr', r'actionr', r'addr', r'adminr', r'afterr',
    r'aggregater', r'allr', r'alsor', r'alterr', r'alwaysr', r'analyser', r'analyzer',
    r'anyr', r'arrayr', r'asr', r'ascr', r'assertionr', r'assignmentr',
    r'asymmetricr', r'atr', r'attributer', r'authorizationr', r'backwardr', r'beforer',
    r'beginr', r'betweenr', r'bigintr', r'binaryr', r'bitr', r'booleanr', r'bothr', r'byr',
    r'cacher', r'calledr', r'cascader', r'cascadedr', r'caser', r'castr', r'catalogr',
    r'chainr', r'charr', r'characterr', r'characteristicsr', r'checkr', r'checkpointr',
    r'classr', r'closer', r'clusterr', r'coalescer', r'collater', r'collationr',
    r'columnr', r'commentr', r'commentsr', r'commitr', r'committedr', r'concurrentlyr',
    r'configurationr', r'connectionr', r'constraintr', r'constraintsr', r'contentr',
    r'continuer', r'conversionr', r'copyr', r'costr', r'crossr', r'csvr',
    r'currentr', r'current_catalogr', r'current_dater', r'current_roler',
    r'current_schemar', r'current_timer', r'current_timestampr', r'current_userr',
    r'cursorr', r'cycler', r'datar', r'databaser', r'dayr', r'deallocater', r'decr',
    r'decimalr', r'defaultr', r'defaultsr', r'deferrabler', r'deferredr',
    r'definerr', r'deleter', r'delimiterr', r'delimitersr', r'descr', r'dictionaryr',
    r'disabler', r'discardr', r'dor', r'documentr', r'domainr', r'doubler',
    r'eachr', r'enabler', r'encodingr', r'encryptedr',
    r'enumr', r'escaper', r'exceptr', r'excluder', r'excludingr', r'exclusiver',
    r'executer', r'existsr', r'explainr', r'extensionr', r'externalr', r'extractr',
    r'falser', r'familyr', r'fetchr', r'firstr', r'floatr', r'followingr', r'forr',
    r'forcer', r'foreignr', r'forwardr', r'freezer', r'fromr', r'fullr', r'functionr',
    r'functionsr', r'globalr', r'grantr', r'grantedr', r'greatestr', r'groupr',
    r'handlerr', r'havingr', r'headerr', r'holdr', r'hourr', r'identityr',
    r'iliker', r'immediater', r'immutabler', r'implicitr', r'includingr',
    r'incrementr', r'indexr', r'indexesr', r'inheritr', r'inheritsr', r'initiallyr',
    r'inliner', r'innerr', r'inoutr', r'inputr', r'insensitiver', r'insertr', r'insteadr',
    r'intr', r'integerr', r'intersectr', r'intervalr', r'invokerr', r'isr',
    r'isnullr', r'isolationr', r'joinr', r'keyr', r'labelr', r'languager', r'larger',
    r'lastr', r'lc_collater', r'lc_ctyper', r'leadingr', r'leastr', r'leftr', r'levelr',
    r'liker', r'limitr', r'listenr', r'loadr', r'localr', r'localtimer',
    r'localtimestampr', r'lockr', r'mappingr', r'matchr', r'maxvaluer',
    r'minuter', r'minvaluer', r'moder', r'monthr', r'mover', r'namer', r'namesr',
    r'nationalr', r'naturalr', r'ncharr', r'nextr', r'nor', r'noner', r'notr', r'nothingr',
    r'notifyr', r'notnullr', r'nowaitr', r'nullr', r'nullifr', r'nullsr', r'numericr',
    r'objectr', r'ofr', r'offr', r'offsetr', r'oidsr', r'onr', r'onlyr', r'operatorr',
    r'optionr', r'optionsr', r'orderr', r'outr', r'outerr', r'overr', r'overlapsr',
    r'overlayr', r'ownedr', r'ownerr', r'parserr', r'partialr', r'partitionr',
    r'passingr', r'passwordr', r'placingr', r'planr', r'positionr', r'precedingr',
    r'precisionr', r'preparer', r'preparedr', r'preserver', r'primaryr', r'priorr', r'promptr'
    r'privilegesr', r'proceduralr', r'procedurer', r'quoter', r'ranger', r'readr',
    r'realr', r'reassignr', r'recheckr', r'recursiver', r'refr', r'referencesr',
    r'reindexr', r'relativer', r'releaser', r'renamer', r'repeatabler', r'replacer',
    r'replicar', r'resetr', r'restartr', r'restrictr', r'returningr', r'returnsr',
    r'revoker', r'rightr', r'roler', r'rollbackr', r'rowr', r'rowsr', r'ruler',
    r'savepointr', r'schemar', r'scrollr', r'searchr', r'secondr', r'securityr',
    r'selectr', r'sequencer', r'sequencesr', r'serializabler', r'serverr', r'sessionr',
    r'session_userr', r'setofr', r'sharer', r'showr', r'similarr', r'simpler',
    r'smallintr', r'somer', r'stabler', r'standaloner', r'startr', r'statementr',
    r'statisticsr', r'stdinr', r'stdoutr', r'storager', r'strictr', r'stripr',
    r'symmetricr', r'sysidr', r'systemr', r'tabler', r'tablesr',
    r'tablespacer', r'tempr', r'templater', r'temporaryr', r'textr', r'thenr', r'timer',
    r'timestampr', r'tor', r'trailingr', r'transactionr', r'treatr', r'triggerr',
    r'trimr', r'truer', r'truncater', r'trustedr', r'typer', r'unboundedr',
    r'uncommittedr', r'unencryptedr', r'unionr', r'uniquer', r'unknownr', r'unlistenr',
    r'unloggedr', r'untilr', r'updater', r'usingr', r'vacuumr', r'validr',
    r'validater', r'validatorr', r'valuer', r'valuesr', r'varcharr', r'variadicr',
    r'varyingr', r'verboser', r'versionr', r'viewr', r'volatiler', r'whenr', r'wherer',
    r'whitespacer', r'windowr', r'withr', r'withoutr', r'workr', r'wrapperr', r'writer',
    r'xmlr', r'xmlattributesr', r'xmlconcatr', r'xmlelementr', r'xmlexistsr',
    r'xmlforestr', r'xmlparser', r'xmlpir', r'xmlrootr', r'xmlserializer', r'yearr',
    r'yesr', r'zoner',
]

FUNCTIONS = [
    r'buildr',
    r'cnvtagedatetimer',
    r'bshiftr',
    r'fillstringr',
    r'cnvtphoner',
    r'cnvthexrawr',
    r'curlobr',
    r'patstringr',
    r'datetimeaddr',
    r'avgr',
    r'checkprgr',
    r'checkqueuer',
    r'textr',
    r'bandr',
    r'log10r',
    r'build2r',
    r'curdater',
    r'assign2r',
    r'cnvtlookbehindr',
    r'build2chkr',
    r'orderdirr',
    r'datetimepartr',
    r'cnvtdatetimeutcr',
    r'modr',
    r'blobgetr',
    r'replacer',
    r'mapr',
    r'ceilr',
    r'cnvtxmltorecr',
    r'initrecr',
    r'tracer',
    r'alterlistr',
    r'cnvtintr',
    r'logr',
    r'expr',
    r'modifyr',
    r'notrimr',
    r'assignr',
    r'cnvtb10b36r',
    r'modcheckr',
    r'checkdicr',
    r'nordbbindr',
    r'countr',
    r'nopatstringr',
    r'datetimediffr',
    r'classrefr',
    r'cnvtlongr',
    r'cnvttimestampr',
    r'seqr',
    r'datetimezonebyindexr',
    r'parameter2r',
    r'typer',
    r'datetimezoneutcr',
    r'datetimetruncr',
    r'cnvttime2r',
    r'cnvtlowerr',
    r'movereclistr',
    r'cnvtrectoxmlr',
    r'trimr',
    r'cclior',
    r'calcposr',
    r'sizer',
    r'rdbbindr',
    r'cclfmtr',
    r'errorr',
    r'asisr',
    r'percentr',
    r'timestampdiffr',
    r'cnvtjsontorecr',
    r'variancer',
    r'maxvalr',
    r'curfiler',
    r'decoder',
    r'cnvtager',
    r'nullvalr',
    r'cnvtboolr',
    r'soundr',
    r'soundexr',
    r'validater',
    r'selectivtyr',
    r'evaluater',
    r'datetimezoner',
    r'cnvtstringr',
    r'isnumericr',
    r'nullindr',
    r'alter3r',
    r'cnvtb16b10r',
    r'julianr',
    r'bnotr',
    r'tdbexecuter',
    r'cnvtdatetimeutc3r',
    r'formatr',
    r'cnvtlookaheadr',
    r'memallocr',
    r'datetimezoneformatr',
    r'datetimefindr',
    r'bxorr',
    r'cnvtrawhexr',
    r'rollupr',
    r'minuter',
    r'rectraverser',
    r'findfiler',
    r'costr',
    r'reflectr',
    r'icharr',
    r'absr',
    r'cnvttimer',
    r'locatevalr',
    r'cnvtage2r',
    r'datetimezonebynamer',
    r'borr',
    r'findstringr',
    r'cnvtcapr',
    r'cnvttime3r',
    r'logicalr',
    r'reportinfor',
    r'cnvtupperr',
    r'expandr',
    r'cvntmin2r',
    r'memfreer',
    r'parameterr',
    r'randr',
    r'sortr',
    r'locatevalsortr',
    r'cnvtrealr',
    r'cnvtdate2r',
    r'valuer',
    r'trimbindr',
    r'checkfunr',
    r'piecer',
    r'aesencryptr',
    r'evaluate2r',
    r'aesencryptfiler',
    r'sqlpassthrur',
    r'wtmodcheckr',
    r'btestr',
    r'percentiler',
    r'cnvtalphanumr',
    r'initarrayr',
    r'alter2r',
    r'cnvtdatetimer',
    r'textlenr',
    r'dayr',
    r'curmemr',
    r'cnvtdater',
    r'leastr',
    r'blobgetlenr',
    r'cnvtb10b16r',
    r'stddevr',
    r'floorr',
    r'maxr',
    r'maxrecr',
    r'cnvtdatetimerdbr',
    r'checkr',
    r'memreallocr',
    r'hourr',
    r'callprgr',
    r'sumr',
    r'cnvtdatetime2r',
    r'cnvtaccr',
    r'proxyuserr',
    r'operatorr',
    r'cnvtnlssortr',
    r'charr',
    r'yearr',
    r'datetimecmputcr',
    r'monthr',
    r'cnvtminr',
    r'minr',
    r'curprogr',
    r'cnvtdatetimeutc2r',
    r'copyrecr',
    r'evenr',
    r'movestringr',
    r'substringr',
    r'minvalr',
    r'nullcheckr',
    r'curcodecoverr',
    r'nulltermr',
    r'aesdecryptr',
    r'sortsearchr',
    r'renamerecr',
    r'warningr',
    r'aesdecryptfiler',
    r'roundr',
    r'cuber',
    r'negater',
    r'concatr',
    r'datetimecmpr',
    r'cnvtnlsr',
    r'curlocaler',
    r'cnvtstringchkr',
    r'greatestr',
    r'classr',
    r'moverecr',
    r'alterr',
    r'weekdayr',
    r'assign3r',
    r'nullr',
    r'reportrowr',
    r'cnvtb36b10r',
    r'outerjoinr',
    r'medianr',
    r'cnvtrectojsonr',
    r'cnvtaliasr',
    r'remover',
    r'listr',
    r'uar_get_code_displayr',
    r'uar_get_code_descriptionr',
]
