# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosourcecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_run_project', '[DjangoSourceControl]: Can run projects'), ('can_add_project', '[DjangoSourceControl]: Can add projects'))},
        ),
    ]
