---
- name: Creating the Searchlight service and endpoint
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_service
    -a "service_name=searchlight
        service_type=search
        description='Openstack Index Service'
        endpoint_region={{ openstack_region_name }}
        url='{{ item.url }}'
        interface='{{ item.interface }}'
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_searchlight_auth }}' }}"
    -e "{'openstack_searchlight_auth':{{ openstack_searchlight_auth }}}"
  register: searchlight_endpoint
  changed_when: "{{ searchlight_endpoint.stdout.find('localhost | SUCCESS => ') != -1 and (searchlight_endpoint.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: searchlight_endpoint.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ searchlight_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ searchlight_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ searchlight_public_endpoint }}'}

- name: Creating the Searchlight project, user, and role
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_user
    -a "project=service
        user=searchlight
        password={{ searchlight_keystone_password }}
        role=admin
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_searchlight_auth }}' }}"
    -e "{'openstack_searchlight_auth':{{ openstack_searchlight_auth }}}"
  register: searchlight_user
  changed_when: "{{ searchlight_user.stdout.find('localhost | SUCCESS => ') != -1 and (searchlight_user.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: searchlight_user.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
