# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/metainformation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dstore/engine/metainformation.proto',
  package='dstore.engine.metainformation',
  syntax='proto3',
  serialized_pb=_b('\n#dstore/engine/metainformation.proto\x12\x1d\x64store.engine.metainformation\"k\n\x0fMetaInformation\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.dstore.engine.metainformation.Types\x12\x13\n\x0binformation\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t*2\n\x05Types\x12\n\n\x06UNKOWN\x10\x00\x12\x0e\n\nSQL_STRING\x10\x01\x12\r\n\tEXEC_TIME\x10\x02\x42Q\n\x10io.dstore.engineB\x15\x45ngineMetaInformationZ&gosdk.dstore.de/engine/metainformationb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPES = _descriptor.EnumDescriptor(
  name='Types',
  full_name='dstore.engine.metainformation.Types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQL_STRING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXEC_TIME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_TYPES)

Types = enum_type_wrapper.EnumTypeWrapper(_TYPES)
UNKOWN = 0
SQL_STRING = 1
EXEC_TIME = 2



_METAINFORMATION = _descriptor.Descriptor(
  name='MetaInformation',
  full_name='dstore.engine.metainformation.MetaInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dstore.engine.metainformation.MetaInformation.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='information', full_name='dstore.engine.metainformation.MetaInformation.information', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='dstore.engine.metainformation.MetaInformation.details', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=177,
)

_METAINFORMATION.fields_by_name['type'].enum_type = _TYPES
DESCRIPTOR.message_types_by_name['MetaInformation'] = _METAINFORMATION
DESCRIPTOR.enum_types_by_name['Types'] = _TYPES

MetaInformation = _reflection.GeneratedProtocolMessageType('MetaInformation', (_message.Message,), dict(
  DESCRIPTOR = _METAINFORMATION,
  __module__ = 'dstore.engine.metainformation_pb2'
  # @@protoc_insertion_point(class_scope:dstore.engine.metainformation.MetaInformation)
  ))
_sym_db.RegisterMessage(MetaInformation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020io.dstore.engineB\025EngineMetaInformationZ&gosdk.dstore.de/engine/metainformation'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
