# coding: utf-8
# Generated by setup.py for PyCBC on 2016-12-06 14:12:39 +0000.

version = '1.6.1'
date = '2016-12-06 13:48:51 +0000'
release = True
last_release = '1.6.1'

git_hash = '88a6d74ccb81a3515f38077e022c85f0fb4df702'
git_branch = 'None'
git_tag = 'v1.6.1'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2016-12-06 14:12:39 +0000'
git_verbose_msg = """Branch: None
Tag: v1.6.1
Id: 88a6d74ccb81a3515f38077e022c85f0fb4df702
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2016-12-06 14:12:39 +0000
Repository status is CLEAN: All modifications committed"""