language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - travis_retry pip install -q -r requirements.txt
  - travis_retry pip install -q -r test-requirements.txt
  - travis_retry python setup.py -q install
script:
  - flake8
  - nosetests --with-coverage --cover-html --cover-package='tvdbapi_client'
after_success: coveralls
