---
- name: Pulling solum-api image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ solum_api_image_full }}"
  when: inventory_hostname in groups['solum-api']

- name: Pulling solum-worker image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ solum_worker_image_full }}"
  when: inventory_hostname in groups['solum-worker']

- name: Pulling solum-deployer image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ solum_deployer_image_full }}"
  when: inventory_hostname in groups['solum-deployer']

- name: Pulling solum-conductor image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ solum_conductor_image_full }}"
  when: inventory_hostname in groups['solum-conductor']
