# coding: utf-8
# Generated by setup.py for PyCBC on 2016-12-08 15:22:06 +0000.

version = '1.6.2'
date = '2016-12-08 13:44:46 +0000'
release = True
last_release = '1.6.2'

git_hash = 'bed7c4f75738345d565f05f72b363399c76e55f2'
git_branch = 'None'
git_tag = 'v1.6.2'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2016-12-08 15:22:06 +0000'
git_verbose_msg = """Branch: None
Tag: v1.6.2
Id: bed7c4f75738345d565f05f72b363399c76e55f2
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2016-12-08 15:22:06 +0000
Repository status is CLEAN: All modifications committed"""