# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('786ms_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoken',
            name='token',
            field=models.CharField(default=b'E497D68D', editable=False, max_length=8, unique=True),
        ),
    ]
