Flora:
  OwnerID: 'ID'
  BotID: 'ID'
  Prefix:
    - 'PREFIX'
    - 'OPTIONAL PREFIX'
    - 'OPTIONAL PREFIX'
  Token: 'TOKEN'
  Plugins:
    - Plugins.Plugin # Just an example, this is a file/package in Plugins.Plugin
  SelfBot: False
  Password: "Only Use This IF you arn't using --selfbot for selfbot"

SelfBot:
  OwnerID: 'YOUR ID'
  BotID: 'Flora BotID'
  Prefix:
    - 'PREFIX'
    - 'OPTIONAL PREFIX'
    - 'OPTIONAL PREFIX'
  Token: 'TOKEN'
  SelfBot: True
  Password: 'Discord Password'
  Plugins: []

Blacklist:
  - 'ID'
