# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160818_1243'),
        ('students', '0026_auto_20160706_0247'),
    ]

    operations = [
    ]
