
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.9.1',
    'branch_nick': '(no',
    'revision_id': 'b478fbd4f2610297dde3cbccec852a19c2a2ffd8',
    'revno': 4554
}
