
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ee1ededd9760f4795a00612521dedd1a92073762",
 "version": "0.3.4.b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
