
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-09T11:39:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b124e2c7eb2c3df043a9069f09c7e7c785eb88e",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
