# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0003_userlocation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fbuserprofile',
            table='djm_user',
        ),
        migrations.AlterModelTable(
            name='getstartedbutton',
            table='db_getstarted',
        ),
        migrations.AlterModelTable(
            name='greetings',
            table='djm_greetings',
        ),
        migrations.AlterModelTable(
            name='persistentmenu',
            table='djm_persistentmenu',
        ),
        migrations.AlterModelTable(
            name='userlocation',
            table='djm_userlocation',
        ),
    ]
