# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0007_auto_20160823_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuserprofile',
            name='first_name',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='gender',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='locale',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='profile_pic',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='psid',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fbuserprofile',
            name='timezone',
            field=models.SmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='greetings',
            name='text',
            field=models.CharField(help_text='This is the greeting text your user will see when the userinteracts with your page in the first time on Messenger. You can only configure 1 of this, text length limit is160 chars.', max_length=160, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='body',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='persistentmenu',
            name='title',
            field=models.CharField(help_text='Button title, case sensitive, unique', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, editable=False, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='mid',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='seq',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='timestamp',
            field=models.BigIntegerField(editable=False, help_text='Facebook returns timestamp as EPOCH'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='url',
            field=models.URLField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='djmessenger.FBUserProfile'),
        ),
    ]
