sudo: false
language: python
python: 2.7
cache:
  directories:
    - buildout-cache
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.1
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.1
  fast_finish: true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
# Try this twice, to avoid a possible problem, on Plone 4.3.7 at
# least, with setuptools as directory instead of zipped egg.
  - bin/buildout -c travis.cfg -N -q || true
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test
after_success: bin/coverage.sh && pip install -q coveralls && coveralls || true
notifications:
  irc: irc.freenode.org#plone-testing
