
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "aeed0808a4f95e1871e9b51505db60283e7be811",
 "version": "0.8.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
