
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "87d6dd3b5d69375bfb471870b009d36bc1ea3432",
 "version": "1.2.73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
