
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e3a6342b2bec17189831d1b454dd56e03ead9348",
 "version": "v1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
