
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2bd41ece3a88476db5918ac54e086191a47b29bf",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
