# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0010_auto_20160824_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('response', models.TextField()),
                ('status_code', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djmessenger.FBUserProfile')),
            ],
            options={
                'db_table': 'djm_sending',
            },
        ),
    ]
