sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev

install:
  - pip install tox-travis

script: tox

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: Jsy58y/wMoNwNJvR0sceN5JSgh+wpmtTEmTnO5b25q0zQBZWhiXwtHAhYiZiKXsifFS9lmVUMCmrfbIpSw6744EQ+tchLwomTrYBfM+Pdo+PemCbwx2E90JtXVrVnzQTNWdbD8pbqJYbACAjAOTnYsshxNs/+nuTMS40KLY90CcYMfAWPAFB4nauXtf/HlpQmnSQFG36ooXhPTogtopzGzlVMum6DQJbu7TYJbKC4c62P0G6evOIntSVQH2WXb/O7f5aIT/qrD3KLH7RXV1Cynvrg/GURlnBIUVsfz1wD6u+JESsvcwdlCcBVAPeZq/CQE9hPr/NUeqHjVDLXzs5Odt/4/khT0wg9BEpFM8E1rgrwIxWYly3l0vCiBw7Wel6skjylixwutp2WO6qnvoztGJCVdAIVExWvRBhyOyfeRmRgX0UUXA39Wth0sDRPpN7cW5T+7qyM+W1J4l60TqJ+E+DOFtZiOam96k04JY4G9OqeDPZUKfZ6lB7EoVXOgVUHt86MvJD1ACwIvK6O54rD4ROINGD4XTyRrTVIRscCbaIPPqv0GA6SR6Mbe9GKfSaXzOJeoy6wGgXjNFAyadBZ+G0UUqGdkm01g9JwYHuinSSlXuK55kF7nQT2hqr7hUYFII2cssQxyj+Rgz2T4uJ1CAmYPEVgpzvxzv1pxUISfE=
  on:
    tags: true
    repo: internap/virtualpdu
