# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('786ms_shops', '0002_saleentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleentry',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
