# coding: utf-8
# Generated by setup.py for PyCBC on 2016-11-18 01:22:21 +0000.

version = '1.5.6'
date = '2016-11-14 02:08:10 +0000'
release = True
last_release = '1.5.7'

git_hash = 'cdf85df008cdb1d92d46e4884e5d48b705fe4430'
git_branch = 'None'
git_tag = 'v1.5.6'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2016-11-18 01:22:21 +0000'
git_verbose_msg = """Branch: None
Tag: v1.5.6
Id: cdf85df008cdb1d92d46e4884e5d48b705fe4430
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2016-11-18 01:22:21 +0000
Repository status is CLEAN: All modifications committed"""