
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f1e04572af022ebd45c2dad028da006778cadcaa",
 "version": "0.post.dev383"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
