
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-03T23:53:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c60bdaa97f6724942ca3819ffdcaffad4c9fa2cb",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
