# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import djmessenger.utils.serializable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('text', models.CharField(help_text='This is the greeting text your user will see when the userinteracts with your page in the first time on Messenger. You can only have 1 of this', max_length=160, primary_key=True, serialize=False, unique=True)),
            ],
            bases=(models.Model, djmessenger.utils.serializable.Serializable),
        ),
    ]
