

input_directory: "%(input_directory)s"
input_pattern: "%(input_pattern)s"
input_extension: "%(input_extension)s"
# =========================================== Sections for the users

# list of your input file
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# =========================================== Sections related to external tools
fastqc:
    options: "--nogroup"

##################################################################
#       MAPPING SECTION
#     Don't forgot to fill sequencing information
##################################################################
sequencing:
    platform: "Illumina"
    instrument: "Hiseq2500"
    flowcell: "C9M8FANXX"

star_mapping:
    do: yes
    prefix_index: /mnt/atlas/PF2_ngs/protected/starGenomes/S_cervS288c
    ref: /mnt/atlas/PF2_ngs/protected/starGenomes/S_cervS288c.fa
    options: ""
    threads: 4
    ram: 30

tophat_mapping:
    do: yes
    prefix_index: /mnt/atlas/PF2_ngs/protected/bowtie_genomes/S_cervS288c
    options: "--no-coverage-search "
    threads: 4

bowtie1_mapping_ref:
    do: yes
    prefix_index: /mnt/atlas/PF2_ngs/protected/bowtie_genomes/S_cervS288c
    options: "--chunkmbs 400 -a --best -q -e50 "
    threads: 4


bowtie1_mapping_rna:
    do: yes
    prefix_index: /mnt/atlas/PF2_ngs/protected/bowtie_genomes/S_cervS288c_rRNA
    options: "" 
    threads: 4

# example of options: "-t exon -g gene_id" for gtf file
feature_counts:
    gff: /mnt/atlas/PF2_ngs/protected/annotation/gff_data/S_cervS288c.gff
    #options: "-t exon -g gene_id"
    options: "-t gene -g ID"
    threads: 2

fastq_screen:
    conf: "fastq_screen.conf"

#################################################################
# Quality trimming and adapter removal
#   - quality: 0 means no trimming, 30 means keep base with quality 
#       above 30
#   - m: 20 means discard trimmed reads that are shorter than 20.
#   - tool: only cutadapt supported for now
#   ref: http://cutadapt.readthedocs.io/
#################################################################
adapter_removal:
    do: yes
    tool: cutadapt
    design: "%(adapter_design)s"
    adapter_type: "%(adapter_type)s"
    fwd: "%(adapter_fwd)s"     
    rev: "%(adapter_rev)s"
    m: 20   # min length cutoff
    M: 120  # max length cutoff
    mode: "g"   # g for 5' adapter, a for 3' and b for both 5'/3'
    quality: "30"
    options: "-O 6 --trim-n"

##################################################################
#       REPORTING SECTION WITH MULTIQC
#
##################################################################

multiqc:
    excluded: "-x *_init_* -x *left_kept_reads* -x *report_rnaseq*"
    output-directory: "multiqc"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Mark duplicates (picard-tools)

mark_duplicates:
    do: yes
    options: ''
