language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
before_install:
    - wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs919/ghostscript-9.19-linux-x86_64.tgz
    - tar -xvf ghostscript-9.19-linux-x86_64.tgz
    - mv ghostscript-9.19-linux-x86_64/gs-919-linux_x86_64 ghostscript-9.19-linux-x86_64/gs
    - export PATH=$PWD/ghostscript-9.19-linux-x86_64:$PATH
install:
    - pip install Pillow coveralls
script:
    - python setup.py test
    - coverage run --source=zplgrf setup.py test
after_success:
    coveralls
notifications:
    email: false
