
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-09T20:35:10+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1c1f09b3b770982a84bfc0c3114ebd4ea2ea15d",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
