
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-09T11:55:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ca23b3bb45a66d933fcf9617dd7a1d8944f0e18",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
