language: python
python:
- '2.7'
- pypy

install:
- pip install -e .
- pip install flake8 yapf
- pip install nose

script:
- yapf -dr hypercompose tests
- flake8 hypercompose/*.py tests
- nosetests tests

deploy:
  provider: pypi
  user: Pierre.Tardy
  on:
    tags: true
    branch: master
  password:
    secure: SwklkOkvzczL4p/MVE3BFXF/sgRB+3tUcMzYOCmfSCaeaIMhCsPETyG2uuwemUUFDkPT0TXg43Z/TRvkQTcCi5amn0A7JJRFEfqPw8Pg22DIgMhRzUcPCjNhCQ/yr82Ku0HEZnHEBNjMSc9tHqMwF5pBS9Ljs5tDVY1yuBLO8iWo268d3yi6yf53VS77T4Bya/xA1nnLDw8Ig8mXR5axWfG4lqVIAqEwP6KLXsuspWoUjXJwvYb9eN8HJhYwKf0izVbjDw6+dewlTWwpU6DNoVpQohybBMn/0Jg61t3A4ViPgg45CvUjfuKKtyICKsgLOAVYKD2MJkkWFG/5mhR3fUou8PJw5N0+vEyFnzhEBwYVWdrk6WF2zhMuVf3yQAAnkSyVspsAtikjJyB3tCtoXiqKKoegoytxnwM9acOTWVkzQ7uaMEJ9Hr/cl5ynttMH9mxzAnjQothi5DKqHqFEvOEZjDEWY1jhv49kLoAq9Uv9aP8OZ7rY24R/LzjjamrN3FN8oyf2D37u7R+P716v49AOUuAc0egYqjvzTorW0UgkGVz8iRowwrFPfJp9zT69dWuIdD3x+jgKzmkuGtZ8PlNvoXqE5CZG24MyXlwZpzUwziTCBOMd7q5DPIK0fobtthXPWza9LI4XfFXMZR1j+Z7N2+iXHLHzC2RcLst8Szs=
env:
  global:
  - hyper_endpoint=tcp://us-west-1.hyper.sh:443
  - secure: M9asZWZwfyBfYn+ajHZvoFS5tWllJc8Ho/WdkH+1HZ7bWyxbVDt7CkkJJZ5DDFvnNxCf34SfSytp0FftEOMNZUSW0nmRLIczQOXrHSGu8FILi1n6hwydAqtKU2T2BW2Cki+MRF2Y0VbF/cAu3sMzDpvQggF8FwBOQwYR2iikjsmMKVAjUf1K/G7FdUPd+G3zkTDqhLlbSHF1Fz7YfBlRypwMfc/tvo4Ag0mhwf9NMxQc/A/mxCZkglPQqcijN4aLyExxX+HH3NBeeR/1GCt8xiuQvRRgWpEso277nZ9HoazVNHwlBnZzRgaCuPBYy+N/WDQaDX+/vqBFywatOLwoF6oh2svx7E0Gf2M11meXARL2woyrxCkamBc3z3gj87KM8sF4RSKyUjc29o51EmPiw7b57PNnkeE7+cDvSAQ6NUYcJWsWGerOwcrdlkHIjTclUwjRFKYEA6B78JCrXsUlObuBKPULFRlL7f13l5qvNuAGWs/8YZDLPwinvzMmtIYyZep1uebSl7Nent0o+Tz+qaCgc65mLtxz8SCX088JghI6UwoZTxqycmzR9mb3VeFxlDlUZiWDdbX5ET1H/5+6qrvCd/gPS68/fVDoXRKMyL9e8xUpjlHw7DVU8XflebIS4zWnb2y5i7uwkiez+U6oLWRBoFHmXtZF+KcfWmyKgpQ=
  - secure: FpMIxsmrzDzVSKs7Of8nt5pyJTy/2vAfYA3X9tJLhzDk9ybvwjA/rexUcOPINEHf0xwxgACwtJYpmVYllzJ6xZ83gjMpfbRqe2ruaYb+zJHLBpjGPuwgTpBu0v2BFH6jhMttx68BINdyr488U2OBdamBiMKnHBygvwovLhjIVgsB0BTR2cd9WmCRoI+T9pzgocpW/WwOHpaOJvFcvcLpLakW4/0IaYE1mzeX8Zn+yIrUh+8gb13HvCJrcK5NRKpyfBV/+8fa1OxGcJ8RJHX08l3/TMyflInG/8e9L35mPPqLQlf9DBm7Bd1yXy/vD7TnoLxx2jgUyV5o/o/6r6sfdhiBBrL9J95QMuuQfQIGMMgZdsagDuP6RhOll04W34ni4BFYneCOpDGoZRrArfGyYDa4Gz3Xikmyz5cCFsPb4kmow0cerxejm3hV9gKeIcnGLZ59CxH6e3r1J5nuqI02vLWiywAjbc+B74t/dq31QS6lfDLbnb5v0Qrvvab/ZHdq+kGtPk7pf/Nzq4erOMSryGYAK11dR0OUhKhoTdYG6x5spZxSpzZUUuaFBGNC2wDIUFmOkBu+W9u/Xfxsaa01uklZAsr9Jmt2PMUqGFd2ZCl5k5hikaWCgNwAHXWyfDfplE7CPS6HEQrPk5/kKx6A+ebEeG0MmtV6RJGyo3LJzfE=
