# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u94f6\u884c\u540d\u79f0')),
                ('logo', models.CharField(max_length=255, verbose_name='\u94f6\u884cLOGO URL')),
                ('color', models.CharField(default='FFFFFF', max_length=8, verbose_name='\u94f6\u884c\u5361\u5e95\u8272')),
            ],
        ),
        migrations.CreateModel(
            name='BankVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_branch', models.TextField(max_length=64, null=True, verbose_name='\u5f00\u6237\u652f\u884c')),
                ('province', models.CharField(default='', max_length=32, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(default='', max_length=16, verbose_name='\u57ce\u5e02')),
                ('card_no', models.CharField(max_length=64, verbose_name='\u5361\u53f7')),
                ('card_tel', models.CharField(max_length=16, verbose_name='\u9884\u7559\u624b\u673a')),
                ('type', models.SmallIntegerField(choices=[(0, '\u5b58\u6298'), (1, '\u501f\u8bb0\u5361'), (2, '\u4fe1\u7528\u5361')], default=1, verbose_name='\u5361\u7c7b\u578b')),
                ('status', models.SmallIntegerField(choices=[(0, '\u7ed1\u5b9a\u6210\u529f'), (1, '\u7ed1\u5b9a\u4e2d'), (2, '\u672a\u4f7f\u7528'), (4, '\u7ed1\u5b9a\u5931\u8d25')], default=0, verbose_name='\u5361\u72b6\u6001')),
                ('stime', models.DateTimeField(auto_now=True, verbose_name='\u72b6\u6001\u65f6\u95f4')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('bank_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_bank_card', to='djdg_common_verify.BankInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=64, null=True, verbose_name='\u8eab\u4efd\u8bc1\u59d3\u540d')),
                ('id_card_no', models.CharField(max_length=32, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('type', models.SmallIntegerField(choices=[(0, '\u5b9e\u540d\u8ba4\u8bc1'), (1, '\u4e0a\u4f20\u8ba4\u8bc1')], default=0, verbose_name='\u8ba4\u8bc1\u7c7b\u578b')),
                ('id_card_img1', models.CharField(max_length=128, null=True, verbose_name='\u8eab\u4efd\u8bc1\u6b63\u9762')),
                ('id_card_img2', models.CharField(max_length=128, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53cd\u800c')),
                ('status', models.SmallIntegerField(choices=[(0, '\u8ba4\u8bc1\u6210\u529f'), (1, '\u5f85\u5ba1\u6838'), (2, '\u672a\u4f7f\u7528'), (4, '\u8ba4\u8bc1\u5931\u8d25')], default=0, verbose_name='\u8ba4\u8bc1\u72b6\u6001')),
                ('stime', models.DateTimeField(auto_now=True, verbose_name='\u72b6\u6001\u65f6\u95f4')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u652f\u4ed8\u5bc6\u7801')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_verified_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
