# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djdg_common_verify', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO `djdg_common_verify_bankinfo` VALUES
        (10, '平安银行', 'http://image.thy360.com/images/bank/logo/ping_an.png',       'E45260'),
        (45, '工商银行', 'http://image.thy360.com/images/bank/logo/gong_shang3.png',   'E45260'),
        (46, '建设银行', 'http://image.thy360.com/images/bank/logo/jian_she3.png',     '4773b5'),
        (47, '农业银行', 'http://image.thy360.com/images/bank/logo/nong_ye3.png',      '1ab091'),
        (48, '中国银行', 'http://image.thy360.com/images/bank/logo/zhong_guo3.png',    'E45260'),
        (49, '招商银行', 'http://image.thy360.com/images/bank/logo/zhao_shang3.png',   'E45260'),
        (50, '交通银行', 'http://image.thy360.com/images/bank/logo/jiao_tong3.png',    '4773b5'),
        (51, '民生银行', 'http://image.thy360.com/images/bank/logo/ming_sheng3.png',   '1ab091'),
        (52, '光大银行', 'http://image.thy360.com/images/bank/logo/guang_da3.png',     'EE9B45'),
        (53, '广发银行', 'http://image.thy360.com/images/bank/logo/guang_fa3.png',     'E45260'),
        (54, '中信银行', 'http://image.thy360.com/images/bank/logo/zhong_xin3.png',    'E45260'),
        (55, '浦发银行', 'http://image.thy360.com/images/bank/logo/pu_fa3.png',        '4773b5'),
        (56, '兴业银行', 'http://image.thy360.com/images/bank/logo/xing_ye3.png',      '4773b5'),
        (57, '杭州银行', 'http://image.thy360.com/images/bank/logo/hang_zhou3.png',    '4773b5'),
        (58, '华夏银行', 'http://image.thy360.com/images/bank/logo/hua_xia3.png',      'E45260'),
        (59, '上海银行', 'http://image.thy360.com/images/bank/logo/shang_hai3.png',    '4773b5'),
        (60, '浙商银行', 'http://image.thy360.com/images/bank/logo/zhe_shang3.png',    'EE9B45'),
        (61, '宁波银行', 'http://image.thy360.com/images/bank/logo/ning_bo3.png',      'EE9B45')
        """
        ),
        ]
