# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('786ms_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleentry',
            name='notes',
            field=models.CharField(default='new customer', max_length=500),
            preserve_default=False,
        ),
    ]
