# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 21:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_prefix', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{2,3}$', message='Only numbers.')], verbose_name='phone prefix')),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only numbers.')], verbose_name='phone number')),
                ('product_id', models.CharField(max_length=100, verbose_name='product id')),
                ('media', models.CharField(max_length=250, verbose_name='media')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
            },
        ),
    ]
