# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:02
from __future__ import unicode_literals

from django.db import migrations
import kernel.utils
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_auto_20160716_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerneluser',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, upload_to=kernel.utils.upload_dir),
        ),
    ]
