# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_getthecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecodefile',
            name='line_numbers',
            field=models.BooleanField(default=False, verbose_name='line numbers'),
        ),
        migrations.AlterField(
            model_name='sourcecodefile',
            name='style',
            field=models.CharField(choices=[('monokai', 'monokai'), ('vim', 'vim'), ('algol', 'algol'), ('autumn', 'autumn'), ('paraiso-dark', 'paraiso-dark'), ('vs', 'vs'), ('xcode', 'xcode'), ('default', 'default'), ('friendly', 'friendly'), ('igor', 'igor'), ('paraiso-light', 'paraiso-light'), ('tango', 'tango'), ('lovelace', 'lovelace'), ('murphy', 'murphy'), ('borland', 'borland'), ('bw', 'bw'), ('trac', 'trac'), ('perldoc', 'perldoc'), ('pastie', 'pastie'), ('manni', 'manni'), ('rrt', 'rrt'), ('native', 'native'), ('algol_nu', 'algol_nu'), ('colorful', 'colorful'), ('emacs', 'emacs'), ('fruity', 'fruity')], default='default', max_length=255, verbose_name='style'),
        ),
    ]
