---
- name: Create SSH Key
  digital_ocean:
    api_token:   "{{ do_token }}"
    name:        "{{ ssh_key_name }}"
    command:     ssh
    state:       present
    ssh_pub_key: "{{ lookup('file', '{{ playbook_dir }}/keys/{{ ssh_key_name }}.pub') }}"
  register: k8sdc_key


# Master Nodes
- name: Create Master Node Droplets
  digital_ocean:
    api_token:    "{{ do_token }}"
    state:        present
    command:      droplet
    name:         "{{ item }}"
    size_id:      "{{ do_masters.do_size }}"
    region_id:    "{{ do_region }}"
    image_id:     centos-7-0-x64
    ssh_key_ids:  "{{ k8sdc_key.ssh_key.id }}"
    unique_name:  true
    private_networking: true
    wait_timeout: 500
  register: k8sdc_master_node_droplets
  with_items: "{{ do_masters.nodes }}"

- name: Add Master Node Droplets to 'k8sdc-master' Group
  add_host: 
    hostname:         "{{ item.droplet.name }}"
    ansible_host: "{{ item.droplet.ip_address }}"
    groups:           k8sdc-master
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/{{ ssh_key_name }}"
  with_items: "{{ k8sdc_master_node_droplets.results }}"


# Nodes
- name: Create Node Droplets
  digital_ocean:
    api_token:    "{{ do_token }}"
    state:        present
    command:      droplet
    name:         "{{ item }}"
    size_id:      "{{ do_nodes.do_size }}"
    region_id:    "{{ do_region }}"
    image_id:     centos-7-0-x64
    ssh_key_ids:  "{{ k8sdc_key.ssh_key.id }}"
    unique_name:  true
    private_networking: true
    wait_timeout: 500
  register: k8sdc_node_droplets
  with_items: "{{ do_nodes.nodes }}"

- name: Add Node Droplets to 'k8sdc-nodes' Group
  add_host: 
    hostname:         "{{ item.droplet.name }}"
    ansible_host: "{{ item.droplet.ip_address }}"
    groups:           k8sdc-nodes
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/{{ ssh_key_name }}"
  with_items: "{{ k8sdc_node_droplets.results }}"


  # Etcd Nodes
- name: Create Etcd Node Droplets
  digital_ocean:
    api_token:    "{{ do_token }}"
    state:        present
    command:      droplet
    name:         "{{ item }}"
    size_id:      "{{ do_etcd.do_size }}"
    region_id:    "{{ do_region }}"
    image_id:     centos-7-0-x64
    ssh_key_ids:  "{{ k8sdc_key.ssh_key.id }}"
    unique_name:  true
    private_networking: true
    wait_timeout: 500
  register: k8sdc_etcd_node_droplets
  with_items: "{{ do_etcd.nodes }}"

- name: Add Etcd Node Droplets to 'etcd' Group
  add_host: 
    hostname:         "{{ item.droplet.name }}"
    ansible_host: "{{ item.droplet.ip_address }}"
    groups:           etcd
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/{{ ssh_key_name }}"
  with_items: "{{ k8sdc_etcd_node_droplets.results }}"


  # Fileserver Node
- name: Create Fileserver Node Droplet
  digital_ocean:
    api_token:    "{{ do_token }}"
    state:        present
    command:      droplet
    name:         "{{ item }}"
    size_id:      "{{ do_fileserver.do_size }}"
    region_id:    "{{ do_region }}"
    image_id:     centos-7-0-x64
    ssh_key_ids:  "{{ k8sdc_key.ssh_key.id }}"
    unique_name:  true
    private_networking: true
    wait_timeout: 500
  register: k8sdc_fileserver_node_droplets
  with_items: "{{ do_fileserver.nodes }}"

- name: Add Fileserver Node Droplet to 'fileserver' Group
  add_host: 
    hostname:         "{{ item.droplet.name }}"
    ansible_host: "{{ item.droplet.ip_address }}"
    groups:           fileserver
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/{{ ssh_key_name }}"
  with_items: "{{ k8sdc_fileserver_node_droplets.results }}"

