
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-02T16:16:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "49268c8ab83acf4e429751372d7d60be372a7837",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
