# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0004_auto_20160826_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ActivityStatus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='collaboration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.CollaborationType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_aid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.AidType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_currency', to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_finance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.FinanceType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_flow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.FlowType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_tied_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.TiedStatus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reporting_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_reporting_organisation', to='iati.Organisation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ActivityScope'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_budget_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_budget_currency', to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Organisation'),
        ),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.OrganisationRole'),
        ),
        migrations.AlterField(
            model_name='activitypolicymarker',
            name='policy_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.PolicyMarker'),
        ),
        migrations.AlterField(
            model_name='activitypolicymarker',
            name='policy_significance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.PolicySignificance'),
        ),
        migrations.AlterField(
            model_name='activitypolicymarker',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Vocabulary'),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Sector'),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Vocabulary'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.BudgetType'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ConditionType'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ContactType'),
        ),
        migrations.AlterField(
            model_name='crsaddloanstatus',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='repayment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.LoanRepaymentPeriod'),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='repayment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.LoanRepaymentType'),
        ),
        migrations.AlterField(
            model_name='description',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Language'),
        ),
        migrations.AlterField(
            model_name='description',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_type', to='iati.DescriptionType'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.DocumentCategory'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='file_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.FileFormat'),
        ),
        migrations.AlterField(
            model_name='location',
            name='adm_country_iso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='adm_vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_vocabulary', to='iati.GeographicVocabulary'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.DescriptionType'),
        ),
        migrations.AlterField(
            model_name='location',
            name='exactness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.GeographicExactness'),
        ),
        migrations.AlterField(
            model_name='location',
            name='feature_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_designation', to='iati.LocationType'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gazetteer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.GazetteerAgency'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.GeographicLocationClass'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id_vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_id_vocabulary', to='iati.GeographicVocabulary'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_reach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.GeographicLocationReach'),
        ),
        migrations.AlterField(
            model_name='location',
            name='precision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.GeographicalPrecision'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_location_type', to='iati.LocationType'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.OrganisationType'),
        ),
        migrations.AlterField(
            model_name='planneddisbursement',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='relatedactivity',
            name='type',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.RelatedActivityType'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultType'),
        ),
        migrations.AlterField(
            model_name='resultindicator',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorMeasure'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.SectorCategory'),
        ),
        migrations.AlterField(
            model_name='title',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Language'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='aid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.AidType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.DescriptionType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='disbursement_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.DisbursementChannel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='finance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.FinanceType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='flow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.FlowType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_providing_organisation', to='iati.Organisation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiving_organisation', to='iati.Organisation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tied_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.TiedStatus'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.TransactionType'),
        ),
    ]
