
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1d82748831b63d24efbb6bafb7aa7206fa2d8633",
 "version": "0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
