
/* #########################################################################
 * [2016-12-07 14:09:57.542000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___BASE_NODE_RPC___
#define ___BASE_NODE_RPC___

#include "BaseNodeRpc/Properties.h"
#include "BaseNodeRpc/CommandProcessor.h"

#endif  // #ifndef ___BASE_NODE_RPC___

