language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script: python test/fetch_examples.py
# command to run tests, e.g. python setup.py test
script: python setup.py test
