
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-19T11:05:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "45cbb2db83e499914154a10877c988b91b2faf79",
 "version": "0.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
