# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerneluser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 16, 10, 15, 34, 511977, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kerneluser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 16, 10, 15, 37, 327467, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kerneluser',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='External Code'),
        ),
    ]
