
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-12-08T11:12:19-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1db09bd10dff837bef3b1d69e97e7de03323f547",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
