zookeeper:
  image: wurstmeister/zookeeper
kafka:
  image: jcnnghm/kafka:latest
  links:
    - zookeeper:zk
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ADVERTISED_PORT: 9092
schematizerdatabase:
  image: docker-dev.yelpcorp.com/schematizer_database:latest
schematizerconfigs:
  image: docker-dev.yelpcorp.com/schematizer_configs:latest
schematizer:
  image: docker-dev.yelpcorp.com/schematizer_service:latest
  links:
    - schematizerdatabase
  volumes_from:
    - schematizerconfigs
  command: "/code/virtualenv_run/bin/python /code/serviceinitd/internal_schematizer start-dev"
