# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cenvars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inheritance',
            name='offspring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='django_cenvars.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='inheritance',
            unique_together=set([('offspring', 'ascendant')]),
        ),
    ]
